export const L=(zh,en)=>({zh,en});
export const text=(value,lang='zh')=>typeof value==='string'?value:value?.[lang]??value?.zh??'';
export const ASSET='/assets/lol/';
export const SOURCE_URL='https://dlarkus6pgedgdu9.usttp.larksuite.com/docx/XvDVdcj5HonPppxZosWuCGRUtHc';
export const introPreviews=[
 {id:'pass',image:'pass-clean.webp',label:L('通行证','Battle pass'),question:L('这份奖励，还要玩多久？','Time to the reward?'),value:'10–15',unit:L('小时','hours'),detail:L('还差 3,000 BXP · 估算示例','3,000 BXP remaining · example estimate'),alt:L('通行证目标提示方案预览','Preview of the battle-pass target proposal')},
 {id:'loading',image:'loading-base.webp',label:L('加载页','Loading screen'),question:L('这局的匹配公平吗？','A fair match?'),value:'1,570',unit:L('/ 1,575','/ 1,575'),detail:L('双方队伍均分 · 示例数据','Team averages · example data'),alt:L('加载页队伍均分方案预览','Preview of the team comparison proposal')},
 {id:'clash',image:'b3-clash-hub-clean.webp',label:L('无畏杯','Fearless Cup'),question:L('看完比赛，自己打一场。','Play after watching.'),value:'BO3',unit:L('全程无畏','Full Fearless'),detail:L('周六常规杯赛，周日冠军组','Ordinary Clash Saturday, champions Sunday'),alt:L('两天制无畏杯赛事中心方案预览','Preview of the two-day Fearless Cup event hub')},
];
export const sourceFigures={
 'c0-system-annotated.webp':{width:1600,height:708,caption:L('图 1：全年运营链路与三个问题点','Figure 1: the live-operations loop and three problems')},
 'a1-pass-official-annotated.webp':{width:1600,height:900,caption:L('图 2：官方 2025 通行证参考，保留原文标注','Figure 2: official 2025 battle pass, with source annotations')},
 'a2-loading-official-annotated.webp':{width:1600,height:1200,caption:L('图 3：Riot 2022 加载页参考，保留原文标注','Figure 3: Riot’s 2022 loading screen, with source annotations')},
 'b1-pass-redesign-annotated.webp':{width:1600,height:900,caption:L('图 4：通行证目标提示方案','Figure 4: the battle-pass target proposal')},
 'b2-loading-redesign-annotated.webp':{width:1600,height:1200,caption:L('图 5：加载页队伍均分方案','Figure 5: team averages on the loading screen')},
 'b3-clash-hub-annotated.webp':{width:1600,height:900,caption:L('图 6：无畏杯赛事中心原始概念图','Figure 6: the original Fearless event-hub concept')},
 'b4-clash-scout-annotated.webp':{width:1600,height:900,caption:L('图 7：侦察阶段与系列赛已用英雄','Figure 7: scouting and previous series picks')},
 'b5-clash-draft-annotated.webp':{width:1600,height:900,caption:L('图 8：已用英雄锁定的禁选界面','Figure 8: draft screen with previous picks locked')},
 'b6-clash-champion-annotated.webp':{width:1600,height:900,caption:L('图 9：冠军结算页原始概念图','Figure 9: the original championship-results concept')},
 'c1-pass-time-annotated.webp':{width:1600,height:593,caption:L('图 10：剩余 3,000 BXP 在不同速度下的时间估算','Figure 10: time estimates for 3,000 BXP at different rates')},
 'c2-gap-dist-annotated.webp':{width:1600,height:747,caption:L('图 11：20,000 局模拟的差距分布','Figure 11: gap distribution across 20,000 simulated matches')},
 'c3-clash-format-annotated.webp':{width:1600,height:593,caption:L('图 12：四种赛制的夺冠路径时间','Figure 12: time to title across four formats')},
 'c4-roadmap-annotated.webp':{width:1600,height:1007,caption:L('图 13：建议上线计划，尚未实施','Figure 13: a proposed rollout, not yet implemented')},
};
export const sources=[
 ['25.13',L('25.13：周任务保留 21 天','25.13: weekly missions retained for 21 days'),'https://www.leagueoflegends.com/en-gb/news/game-updates/patch-25-13-notes/'],
 ['25.17',L('25.17：通行证缩短到 48 级','25.17: a 48-level pass'),'https://www.leagueoflegends.com/en-sg/news/game-updates/patch-25-17-notes/'],
 ['pass-ui',L('2025 赛季与新通行证，2024-11-25','Seasons in 2025, published 25 Nov 2024'),'https://www.leagueoflegends.com/en-us/news/dev/dev-seasons-in-2025/'],
 ['loading-ui',L('挑战系统与加载页，2022-05-06','Challenges and the loading screen, 6 May 2022'),'https://www.leagueoflegends.com/en-us/news/game-updates/challenges-walkthrough/'],
 ['26.3',L('26.3：Climb Indicator','26.3: Climb Indicator'),'https://www.leagueoflegends.com/en-gb/news/game-updates/patch-26-3-notes/'],
 ['26.15',L('26.15：补位机制调整','26.15: autofill changes'),'https://www.leagueoflegends.com/en-us/news/game-updates/league-of-legends-patch-26-15-notes/'],
 ['clash-faq',L('冠军杯赛 FAQ','Clash FAQ'),'https://support.riotgames.com/en-us/league-of-legends/events/clash-faq'],
 ['worlds2020',L('Worlds 2020 冠军杯赛','Worlds 2020 Clash'),'https://www.leagueoflegends.com/en-us/news/game-updates/worlds-2020-clash-details/'],
 ['clash2023',L('2023 冠军杯赛调整','Clash changes in 2023'),'https://www.leagueoflegends.com/en-us/news/dev/clash-changes-and-split-2-schedule/'],
 ['smurfs',L('Ask Riot：冠军杯赛的小号问题','Ask Riot: smurfs in Clash'),'https://www.leagueoflegends.com/en-us/news/dev/ask-riot-smurfs-in-clash/'],
 ['clash-wiki',L('LoL Wiki：冠军杯赛流程','LoL Wiki: Clash format'),'https://wiki.leagueoflegends.com/en-us/Clash'],
 ['fearless',L('LoL Esports：2025 与无畏征召','LoL Esports in 2025 and Fearless Draft'),'https://lolesports.com/en-GB/news/lol-esports-in-2025'],
 ['dota',L('Dota 2 Wiki：周末杯赛','Dota 2 Wiki: Weekend Battle Cup'),'https://dota2.fandom.com/wiki/Weekend_Battle_Cup'],
 ['premier',L('VALORANT：Premier FAQ','VALORANT: Premier FAQ'),'https://playvalorant.com/en-us/news/game-updates/premier-global-open-beta-faq/'],
 ['kpl',L('王者荣耀：2024 KPL 资格赛规则','Honor of Kings: 2024 KPL qualifier rules'),'https://pvp.qq.com/gicp/news/651/623058.html'],
];
export const chapters=[
 {id:'pass',label:L('通行证','Battle pass'),index:'01',title:L('这份奖励，\n还要玩多久？','Time to\nthe reward you want.'),summary:L('在奖励详情里显示剩余经验，按近期对局估算时间。','Show remaining XP in reward details, then estimate time from recent matches.'),problem:L('等级和本级经验都在，但离目标还有多远，要靠玩家自己换算。断档回来的人尤其难判断是否还赶得上。','The level is visible. The remaining commitment is not. Returning players must calculate whether a reward is still within reach.'),change:L('沿用奖励详情区，补上「设为目标」、剩余经验和个人时间估算。','Keep the reward detail panel. Add a target, remaining XP and a personal time estimate.'),limit:L('时间是估算，不是承诺。样本不足时只显示经验差；不提前计入未完成任务。','Time is an estimate, not a promise. With insufficient history, show XP only. Unfinished missions are not counted in advance.'),cost:'12',costLabel:L('人周 / 估算','person-weeks / estimate'),decision:L('优先实施','First to implement')},
 {id:'loading',label:L('加载页','Loading screen'),index:'02',title:L('这局的匹配，\n公平吗？','A fair match,\nexplained.'),summary:L('用双方整体实力的对比，替换一条与本局无关的小贴士。','Replace a generic tip with a comparison of the two teams.'),problem:L('玩家看到的是段位，匹配使用的是隐藏分。两者的落差，让一次失败很容易变成对匹配的怀疑。','Players see ranks; matchmaking uses an estimate of skill. The difference makes a loss easy to read as unfair matchmaking.'),change:L('只在队伍层面解释差距，不把个人隐藏分变成开局前的标签。','Explain the gap at team level, without turning personal MMR into a pre-game label.'),limit:L('均值无法解释每条线的对位。展示也可能引发新的争议，因此先做理解测试，再决定是否上线。','Averages hide lane-level differences, and extra information may create new arguments. Test understanding before a release decision.'),cost:'2',costLabel:L('人周 / 先做测试','person-weeks / initial research'),decision:L('先验证理解','Test understanding first')},
 {id:'clash',label:L('无畏杯','Fearless Cup'),index:'03',title:L('看完世界赛，\n自己打一场。','A Fearless Cup\nfor amateur teams.'),summary:L('周六打常规冠军杯赛，周日由各组冠军参加全程无畏 BO3。','Play ordinary Clash on Saturday, then a full Fearless BO3 for its champions on Sunday.'),problem:L('职业赛的无畏规则带来了新的博弈，但普通玩家缺少对应的赛事入口。','Fearless adds a new strategic layer to professional play, but ordinary players lack an equivalent tournament experience.'),change:L('第 1 天保持常规冠军杯赛；第 2 天，冠军之间用一场全程无畏 BO3 决胜。','Keep ordinary Clash on day one. Pair its champions for a full Fearless BO3 on day two.'),limit:L('只有第 1 天冠军晋级。30 场排位门槛和两天的时间投入，都可能挡住普通玩家；第二天的实际参与率需要试点验证。','Only day-one champions advance. The 30-ranked-game threshold and two-day commitment may exclude ordinary players; day-two participation needs a pilot.'),cost:'32',costLabel:L('人周 / 估算','person-weeks / estimate'),decision:L('先试一个周末','Pilot one weekend')},
];
const table=(headers,rows)=>({headers,rows});
export const evidence={
 pass:[
  {id:'pass-system',title:L('现有系统与官方依据','Current system and supporting sources'),paragraphs:[L('25.13 把周任务保留期从 7 天延长到 21 天；25.17 将通行证从 50 级缩短到 48 级。方案沿着降低追赶成本的方向，补充目标信息。','Patch 25.13 extended weekly mission retention from 7 to 21 days; 25.17 reduced the pass from 50 to 48 levels. This proposal follows that catch-up direction by explaining the target.')],table:table([L('字段','Field'),L('含义与当前值','Meaning / current value'),L('展示状态','Visibility')],[
   ['level_max',L('等级上限：48 级','Maximum level: 48'),L('已有','Existing')],['xp_per_level',L('每级 400–500 BXP，每幕配置','400–500 BXP per level, configured per act'),L('已有','Existing')],['xp_current',L('累计 9,000 BXP，示例 Lv 18','9,000 cumulative BXP, example level 18'),L('只显示本级进度','Only current-level progress shown')],['mission_expire',L('任务保留 21 天','Missions retained for 21 days'),L('任务页已有','Existing mission page')],['act_end',L('示例剩余 18 天 12 小时','Example: 18 days 12 hours left'),L('已有','Existing')],['xp_rate_7d',L('近 7 天每小时经验，由对局记录计算','Hourly XP from the past seven days of match history'),L('新增展示','New presentation')],['target_reward',L('玩家选定的目标奖励','Player-selected reward target'),L('新增字段','New field')]
  ]),images:['a1-pass-official-annotated.webp'],sources:['25.13','25.17','pass-ui']},
  {id:'pass-method',title:L('计算方式与边界情况','Calculation and edge cases'),formula:'T = (X_target − X_now) / v₇d = (12,000 − 9,000) / (200–300) = 10–15 h',paragraphs:[L('X 是累计经验，v 是本人近 7 天每小时获得的经验，包含已完成任务。每局结束后更新；未完成任务的经验不预支。示例速度为假设值。','X is cumulative XP; v is the player’s hourly XP over the past seven days, including completed missions. Update after each match. Do not count unfinished missions. The speeds here are hypothetical.')],table:table([L('情况','Situation'),L('处理','Response')],[
   [L('近 7 天没有对局或样本不足','No recent games or insufficient history'),L('只显示经验差，不估算时间','Show remaining XP without a time estimate')],[L('选了付费奖励，未买通行证','Paid reward without a premium pass'),L('明确注明需要解锁付费通行证','State that a premium pass is required')],[L('当前速度可能赶不上本幕结束','Current pace may miss the act deadline'),L('如实提示可能拿不到，不用倒计时催促','Explain the risk without a pressure countdown')],[L('已经达到目标经验','Target XP already reached'),L('显示已达到目标，不产生负数时间','Show target reached, never negative time')]
  ]),images:['c1-pass-time-annotated.webp','b1-pass-redesign-annotated.webp'],sources:[]},
  {id:'pass-delivery',title:L('投入、收益与验证','Cost, return and validation'),paragraphs:[L('估算 12 人周：策划 2、客户端 5、服务端 3、测试 2。建议进入 2027 赛季第一幕。人周是工作量，不等于日历工期。','Estimated effort: 12 person-weeks: design 2, client 5, server 3, QA 2. Proposed for act one of the 2027 season. Person-weeks measure effort, not elapsed duration.'),L('按 2 万元/人周、每张付费通行证收入 70 元估算，开发成本约 24 万元，需要新增约 3,430 张付费通行证覆盖成本。所有金额都需替换为内部数据。','At an assumed CNY 20,000 per person-week and CNY 70 revenue per premium pass, development costs CNY 240,000, requiring roughly 3,430 additional passes to cover cost. Replace these assumptions with internal figures.')],formula:'240,000 / 70 ≈ 3,430',table:table([L('验证环节','Validation'),L('标准 / 假设','Criterion / assumption')],[
   [L('先做界面理解测试','Initial comprehension test'),L('5–8 名玩家；至少 80% 能说出还要玩多久','5–8 players; at least 80% can explain the remaining time')],[L('回流玩家对照实验','Returning-player controlled experiment'),L('14 天内领到目标奖励的比例高于对照组','A higher share claims their target reward within 14 days')],[L('样本量示例','Illustrative sample size'),L('基线 30%，检测 +2 个百分点，双侧 α=.05、效力 .80：每组约 8,400 人','30% baseline, +2 percentage points, two-sided α=.05, power .80: about 8,400 per arm')]
  ]),formulas:['n = (1.96 + 0.84)² × [0.30 × 0.70 + 0.32 × 0.68] / 0.02² ≈ 8,390'],sources:[]},
 ],
 loading:[
  {id:'loading-system',title:L('段位、隐藏分与展示位置','Rank, MMR and where the change lives'),paragraphs:[L('26.3 的 Climb Indicator 已在段位低于隐藏分时提供提示。作者据此提出：保持个人分数隐藏，只补充队伍级信息。图中沿用的是 Riot 2022-05-06 公布的加载页。','Patch 26.3 introduced a Climb Indicator when rank trails MMR. This proposal keeps individual scores private and adds team-level context. The pictured loading screen is Riot’s 6 May 2022 reference.')],table:table([L('字段','Field'),L('含义','Meaning'),L('可见性','Visibility')],[
   ['rank_tier',L('段位，如黄金 II','Rank, e.g. Gold II'),L('资料页与加载页边框已有','Existing profile / loading border')],['mmr',L('匹配用的实力估计','Skill estimate used for matchmaking'),L('个人具体分数不公开','Individual score remains private')],['team_avg_mmr',L('队伍平均隐藏分','Average team MMR'),L('提案新增队伍级展示','Proposed team-level display')],['loading_tip',L('加载页中间的随机小贴士','Random tip in the loading screen'),L('用队伍实力对比替换','Replace with team comparison')]
  ]),images:['a2-loading-official-annotated.webp','b2-loading-redesign-annotated.webp'],sources:['26.3','loading-ui']},
  {id:'loading-method',title:L('均分公式与 20,000 局模拟','Team averages and 20,000 simulated matches'),formula:'M̄ = (M₁ + M₂ + M₃ + M₄ + M₅) / 5      Δ = |M̄_blue − M̄_red|',paragraphs:[L('蓝方示例：(1,540 + 1,580 + 1,600 + 1,570 + 1,560) ÷ 5 = 1,570；红方 1,575，差距 5。模拟占比来自固定示例模型，不代表真实匹配分布，也不证明展示后举报会下降。','Example blue team: (1,540 + 1,580 + 1,600 + 1,570 + 1,560) / 5 = 1,570; red team 1,575; gap 5. The distribution is a fixed simulation, not live matchmaking data or evidence that this UI reduces reports.')],table:table([L('差距 Δ','Gap Δ'),L('模拟占比','Simulated share'),L('展示文字','Message')],[
   ['< 25','69.4%',L('双方实力接近','Teams are closely matched')],['25 ≤ Δ < 75','29.2%',L('略有差距，并说明哪方稍高','A slight gap, with the stronger team named')],['≥ 75','1.5%',L('显示差距与可核实原因；排队超过 2 分钟后放宽范围仅为示例','Show the gap and a verified reason; a range widened after two minutes is an example only')]
  ]),images:['c2-gap-dist-annotated.webp'],sources:[]},
  {id:'loading-decision',title:L('为什么选队伍均分，为什么先测试','Why team averages, and why test first'),table:table([L('方案','Approach'),L('能回答什么','What it explains'),L('代价与决定','Trade-off / decision')],[
   [L('只显示段位','Rank only'),L('个人可见段位','Visible individual rank'),L('不能说明段位与实力落差；信息不足','Does not explain rank–skill mismatch; insufficient')],[L('公开个人隐藏分','Individual MMR'),L('个人分数信息最全','Most detailed individual information'),L('容易锁定最低分玩家并指责；不采用','Makes the lowest score a target; rejected')],[L('显示队伍均分','Team averages'),L('双方整体是否接近','Whether overall strength is similar'),L('掩盖具体对位差距；采用但先验证','Hides lane-level gaps; proposed, pending tests')]
  ]),paragraphs:[L('完整方案估算 10 人周：客户端 4、服务端 2、用户研究 2、测试 2，约 20 万元。先投入 2 人周做原型理解测试，测试不达标就停止；拟在 2027 年中小范围实验。','Full estimate: 10 person-weeks: client 4, server 2, research 2, QA 2; about CNY 200,000. Start with two person-weeks of prototype research and stop if it fails. A small experiment is proposed for mid-2027.'),L('成功标准：理解正确率上升，赛后举报率和中途退出率不高于对照组。数据异常时退回原有展示；没有可核实原因时不编造解释。','Success: better comprehension, with report and abandonment rates no worse than control. Fall back to the existing display on invalid data. Do not invent a cause if none is verified.')],sources:[]},
 ],
 clash:[
  {id:'clash-system',title:L('现有冠军杯赛与同类产品','Existing Clash and comparable products'),table:table([L('环节','Stage'),L('当前规则（文档研究口径）','Current rules in the source study')],[
   [L('参赛资格','Eligibility'),L('等级 ≥30、手机号短信验证、完成排位定级；手机号解绑后需等 6 个月才能换绑','Level 30+, SMS verification and ranked placements; six-month wait after unlinking a phone number')],[L('分组','Tiers'),L('I–IV 组；计算时偏重队内高分玩家','Tiers I–IV, weighted toward higher-rated teammates')],[L('赛前','Pre-match'),L('开赛前 30 分钟确认，7 分钟侦察，再进入职业赛同款禁选','Lock in 30 minutes before the start; seven minutes of scouting, then tournament draft')],[L('赛制','Format'),L('8 队单淘汰，每轮一局；首轮败者进入安慰赛，每队当天最多 3 局','Eight-team single elimination, one game per round; first-round losers enter consolation; up to three games')],[L('奖励','Rewards'),L('每胜 400 胜利点解锁旗帜、队标；门票与战绩决定法球；冠军奖杯在水晶枢纽展示两周','400 VP per win unlocks banners and logos; orbs depend on ticket and results; trophies appear at the Nexus for two weeks')],[L('选人','Draft'),L('每局独立，不跨局限制英雄','Independent draft per game; no series-wide restrictions')]
  ]),paragraphs:[L('Worlds 2020 曾使用 16 队赛制并发放冠军皮肤。2023 年官方提到 ARAM 冠军杯赛参与度居历届前列，同年将年度赛事从 20 个周末减到 14 个。方案借用“赛事主题＋新玩法”的方向，而非将先例当作本提案的效果证明。','Worlds 2020 used 16-team brackets and champion-skin rewards. In 2023 Riot described strong ARAM Clash participation and reduced the annual schedule from 20 weekends to 14. These precedents motivate a themed format, but do not prove this proposal will succeed.')],extraTables:[table([L('参照','Reference'),L('做法','Approach'),L('启发','Implication')],[
   ['Dota 2 Weekend Battle Cup',L('每周 8 队单淘汰，三连胜夺冠；多数展示奖励仅一周','Weekly eight-team bracket; three wins; most display rewards last a week'),L('把冠军纪念保留更久','Make championship recognition more durable')],['VALORANT Premier',L('固定队伍、每周参赛、水平分级，顶级衔接次级职业联赛','Persistent teams, weekly competition and tiers; a path toward tier-two competition'),L('荣誉与赛事体系产生联系','Connect recognition with a competitive system')],['KPL',L('全局 BP 限制一方重复使用已选英雄','Global BP restricts a side from reusing its previously selected heroes'),L('有跨局英雄限制的认知基础；本提案使用双方共享禁用池的全程无畏','An audience familiar with cross-game restrictions; this proposal uses a shared full-Fearless pool')]
  ])],sources:['clash-faq','clash-wiki','worlds2020','clash2023','smurfs','fearless','dota','premier','kpl']},
  {id:'clash-format',title:L('两天流程与四种赛制的取舍','Two-day flow and four format options'),paragraphs:[L('周六：队长报名 → 验证手机号与门槛 → 开赛前 30 分钟锁定名单 → 常规 8 队杯赛 → 未夺冠结算当日奖励，冠军晋级。周日：同实力组冠军配对 → 每局侦察 7 分钟 → 全程无畏选人 → 比赛 → 系列赛未结束则回到侦察，结束后结算冠军奖励。','Saturday: captain registers → phone and eligibility checks → roster locks 30 minutes before start → ordinary eight-team Clash → non-champions claim day-one rewards; champions advance. Sunday: pair champions within their tier → seven-minute scouting before each game → Fearless draft → play → repeat until the series ends, then award champion rewards.'),L('同一实力组随机配对；冠军数为奇数时，原文提议第 1 天胜利点最高者轮空。胜利点并列、弃赛和第二天名单延续的执行细则，原文尚未定义，试点前需补齐；本网页不模拟这些裁决。','Pair randomly within a tier. For an odd count, the source proposes a bye for the team with the most day-one VP. Ties, forfeits and day-two roster continuity are not specified and must be settled before a pilot; this page does not simulate those rulings.')],table:table([L('赛制','Format'),L('夺冠路径时间','Time to title'),L('同对手系列赛','Same-opponent series'),L('判断','Decision')],[
   [L('普通冠军杯赛','Ordinary Clash'),L('约 2 小时','About 2 h'),L('无','No'),L('现状','Baseline')],[L('A：第 1 天每轮无畏 BO3','A: every day-one round is a Fearless BO3'),L('约 5 小时','About 5 h'),L('有，互耗英雄池','Yes, shared pool depletion'),L('业余队伍时间负担过大','Too much time for amateur teams')],[L('B：第 1 天全日锁自己英雄','B: day-one self-only restrictions'),L('约 2 小时','About 2 h'),L('无，只有自我限制','No, self-restriction only'),L('缺少双方互相消耗的博弈','Lacks head-to-head pool strategy')],[L('C：两天制','C: two-day format'),L('2 + 1.7 小时','2 + 1.7 h'),L('第 2 天全程无畏 BO3','Day-two full Fearless BO3'),L('采用','Selected')]
  ]),formula:'Pₖ = N − 10 − 10(k − 1)      N ≈ 170 → 160 / 150 / 140',extraParagraphs:[L('N≈170 为文档示例英雄总量；每局减去本局 10 个禁用，以及双方此前选过的 10(k−1) 个英雄。默认 2:1 系列赛；2:0 结束后不产生第 3 局。每名玩家应准备至少 3 个能打的英雄。','N≈170 is the document’s illustrative roster size. Subtract ten current bans and ten picks per completed game across both teams. The default demo is a 2:1 series; a 2:0 sweep has no third game. Players should prepare at least three viable champions.')],images:['c3-clash-format-annotated.webp','b3-clash-hub-annotated.webp','b4-clash-scout-annotated.webp','b5-clash-draft-annotated.webp'],sources:[]},
  {id:'clash-fairness',title:L('公平性与参与门槛','Fairness and participation barriers'),table:table([L('风险','Risk'),L('措施','Safeguard'),L('状态','Status')],[
   [L('小号','Smurfs'),L('短信验证、高分玩家加权分组、后台检测；确认违规可撤销全队奖励','SMS verification, weighting toward stronger teammates, detection; confirmed abuse can revoke team rewards'),L('官方已有','Existing')],[L('小号','Smurfs'),L('本赛季单双排至少 30 场，不足时提示差额','At least 30 solo/duo games this season; show the shortfall'),L('提案新增','Proposed')],[L('重复领奖','Duplicate rewards'),L('按现有验证手机号去重，一个号码每届领一次，不向其他玩家公开','Deduplicate using existing verified phone data; one reward per number per event, never publicly displayed'),L('提案新增','Proposed')],[L('代打或换人','Ringers / roster changes'),L('报名后锁名单，当天不能换人；登录设备或地点异常时冻结奖励待审核','Lock the roster for the day; hold rewards for review on anomalous device or location signals'),L('提案新增','Proposed')],[L('消极比赛','Disruptive play'),L('荣誉等级 ≥2，近 30 天无处罚','Honor level 2+ and no penalties in the past 30 days'),L('提案新增','Proposed')]
  ]),paragraphs:[L('30 场门槛可能挡住普通玩家；不设排位门槛的 ARAM 等杯赛仍照常开放。第 2 天只有冠军参加，多数玩家可通过观战、回放和阵容卡参与。如果试点表现良好，下一届才考虑将冠军组扩成 4 队小组赛。','A 30-game threshold may exclude ordinary players; other events such as ARAM Clash stay available. Most players will not reach day two, so spectating, replays and lineup cards provide a connection. A four-team champion-stage group is a later option for the next cup, conditional on the pilot.'),L('避开世界赛决赛观赛时段，安排在决赛前一个周末或决赛后第二天。通过观赛掉落门票衔接“先看，再打”。不新增收集手机号，去重实现仍需隐私与内部流程审查。','Avoid the Worlds final viewing window by scheduling the previous weekend or the next day. Viewing drops connect watching with participation. No additional phone collection is proposed; deduplication still needs internal privacy and process review.')],sources:['smurfs']},
  {id:'clash-rewards',title:L('完整奖励、投入与试点标准','Rewards, cost and pilot criteria'),table:table([L('结果','Result'),L('普通冠军杯赛','Ordinary Clash'),L('无畏杯提案','Fearless Cup proposal')],[
   [L('报名','Entry'),L('购买或活动门票','Purchased or event ticket'),L('观赛可掉落免费门票','A free ticket may drop from viewing')],[L('第 1 天参赛','Day-one entry'),L('按票档和战绩发法球','Orbs based on ticket / results'),L('保留法球，加世界赛无畏图标','Keep orbs; add a Worlds Fearless icon')],[L('每赢 1 局','Every win'),L('400 胜利点','400 VP'),L('400 胜利点 + 500 通行证经验，两天通用','400 VP + 500 BXP on either day')],[L('第 1 天打满 2 局','Complete two day-one games'),L('无对应档次','No equivalent tier'),L('无畏限定表情','Fearless event emote')],[L('第 1 天夺冠','Day-one champion'),L('奖杯展示两周','Trophy displayed for two weeks'),L('保留奖杯，晋级冠军组','Keep trophy; advance to day two')],[L('第 2 天夺冠','Day-two champion'),L('无对应档次','No equivalent tier'),L('永久奖杯、至下一届的加载页称号、系列赛阵容卡','Permanent trophy, loading title until the next cup, series lineup card')],[L('I 组冠军组胜者','Tier-I champion-stage winner'),L('无对应档次','No equivalent tier'),L('额外冠军墙留名一年、当年世界赛冠军皮肤','Also a one-year champions wall entry and that year’s Worlds champion skin')]
  ]),paragraphs:[L('阵容卡按实际局数记录双方系列赛中的冠军队阵容与胜负。3 局为 15 个英雄，2 局为 10 个。奖杯刻上年份和队名，永久进入资料荣誉栏；称号让其他玩家在加载页看到。','The card records the winning team’s lineups and results for games actually played: 15 champions over three games, ten over two. The trophy carries the year and team name in the profile; the title is visible to other players on loading screens.'),L('每胜 500 通行证经验将赛事接回通行证目标。称号、奖杯和展示位的边际内容成本较低；冠军皮肤奖励有 Worlds 2020 先例，但仍应核算成本。','500 BXP per win links the event back to pass goals. Titles, trophies and display slots have low marginal content cost. Worlds 2020 provides a skin-reward precedent, though costs still need accounting.'),L('估算 32 人周：服务端 10、客户端 8、策划 4、美术 4、测试 4、冠军组配对 2。按 2 万元/人周约 64 万元；若参赛 10 万人，开发成本摊算约 6.4 元/人（原文取整约 6 元），并非完整运营获客成本。','Estimate: 32 person-weeks: server 10, client 8, design 4, art 4, QA 4, pairing 2. At CNY 20,000 per person-week: CNY 640,000. With 100,000 participants this allocates CNY 6.4 development cost per participant (rounded to about 6 in the source), not an all-in acquisition cost.'),L('MSI 2027 试一个周末，2027 世界赛再决定正式实施。对比同期普通冠军杯赛：第 1 天报名队伍更多；第 2 天出场英雄种类多于第 1 天；小号举报不增加。','Pilot a weekend at MSI 2027 before a Worlds 2027 rollout decision. Compare with contemporaneous ordinary Clash: more day-one registrations, more distinct champions on day two than day one, and no increase in smurf reports.')],images:['b6-clash-champion-annotated.webp'],sources:['worlds2020']},
 ]
};
export const decisions=[
 {id:'pass',order:'01',title:L('通行证目标提示','Reward target'),effort:'12',when:L('2027 赛季第一幕','2027 season, act one'),action:L('优先做，验证目标理解与领取率','Build first; test comprehension and reward claims'),risk:L('估算失准','Misleading estimates')},
 {id:'clash',order:'02',title:L('世界赛无畏杯','Worlds Fearless Cup'),effort:'32',when:L('MSI 2027 试点','MSI 2027 pilot'),action:L('同步开发，用一个周末验证参与和公平','Develop in parallel; pilot participation and fairness'),risk:L('时间与参赛门槛','Time and eligibility barriers')},
 {id:'loading',order:'03',title:L('加载页队伍均分','Team comparison'),effort:'10',when:L('先研究，再小范围实验','Research before a limited experiment'),action:L('先批 2 人周，理解测试不达标就停止','Start with two person-weeks; stop if research fails'),risk:L('引发新的归因与争议','New blame and disputes')},
];
export const rejected=table([L('没有采用的方向','Rejected direction'),L('原因','Reason')],[
 [L('补位保分评分','Autofill loss protection / grading'),L('原报告提案；26.15 已取消败局保分和评级门槛，不再作为新增改进','Earlier proposal; 26.15 removed loss protection and grade requirements, so it is no longer presented as a new improvement')],
 [L('低信誉玩家隔离队列','Separate low-reputation queue'),L('误判、申诉、队列人数都需要内部数据，外部无法评估','False positives, appeals and queue size require unavailable internal data')],
 [L('公开每个人的隐藏分','Public individual MMR'),L('开局前容易锁定最低分玩家，引发指责','Makes the lowest-rated player a target before the game starts')]
]);
export const coverage=[
 [L('决策摘要与现状问题','Decision summary / current problems'),L('开场、章节导语、推进顺序','Opening, chapter introductions, priorities')],
 [L('通行证系统、方案、公式与成本','Pass system, proposal, formula and cost'),L('通行证演示及三个依据展开区','Pass demo and its three evidence sections')],
 [L('加载页系统、模拟与展示取舍','Loading system, simulation and alternatives'),L('加载页演示及三个依据展开区','Loading demo and its three evidence sections')],
 [L('杯赛现状、竞品、两天流程','Clash baseline, references and two-day flow'),L('无畏杯时间线、现状与赛制依据','Fearless timeline, system and format sections')],
 [L('公平性、奖励、测算与风险','Fairness, rewards, estimates and risks'),L('无畏杯公平性、奖励与试点依据','Fearless safeguards, rewards and pilot sections')],
 [L('结论、实验设计与未选方向','Conclusion, study design and rejected ideas'),L('推进顺序、通行证验证依据、最终附录','Priorities, pass validation and final appendix')],
 [L('13 张原文图、完整正文与来源','13 source figures, complete text and citations'),L('对应章节及完整中文快照下载','Relevant chapters and complete Chinese snapshot')]
];
