import {useEffect,useId,useMemo,useState} from 'react';
import data,{BALL_KEYS,ballNames,calibration,presets,observed,simulations,calculate,parseCounts,text,number,money,recordImage} from './roco-model-core';
import './roco-pages.css';
import ExpressiveTitle from '../components/ExpressiveTitle';

const DEFAULT = {raw:{fairy:'500',advanced:'500',net:'0'},multiplier:2};
const KEY = 'jay-roco-model-v6-inputs';
function initialInput(){try{const saved=JSON.parse(sessionStorage.getItem(KEY));if(saved&&[1,2].includes(saved.multiplier)&&BALL_KEYS.every(key=>typeof saved.raw?.[key]==='string'))return saved;}catch{}return DEFAULT;}

export function ModelCalculator({lang='zh',compact=false}) {
 const en=lang==='en',id=useId();
 const [state,setState]=useState(initialInput);
 const counts=useMemo(()=>parseCounts(state.raw),[state.raw]);
 const result=useMemo(()=>calculate(counts,state.multiplier),[counts,state.multiplier]);
 const ready=result.status==='ready',out=result.outputs;
 useEffect(()=>{try{sessionStorage.setItem(KEY,JSON.stringify(state));}catch{}},[state]);
 const applyPreset=p=>setState({raw:Object.fromEntries(BALL_KEYS.map(key=>[key,String(p.balls[key])])),multiplier:p.income_multiplier_scenario});
 const current=presets.find(p=>BALL_KEYS.every(k=>String(p.balls[k])===state.raw[k])&&p.income_multiplier_scenario===state.multiplier);
 return <div className={`rco-calculator${compact?' is-compact':''}`}>
  <div className="rco-calc-inputs"><div className="rco-panel-heading"><span className="rco-kicker">INPUT / 01</span><h3>{en?'Configure a scenario.':'先设定一次投入。'}</h3><p>{en?'Ball quantities, then the income basis.':'修改球数，再选择收入口径。'}</p></div>
   <div className="rco-preset-grid" aria-label={en?'Audited presets':'已核验预设'}>{presets.map(p=><button type="button" key={p.id} aria-pressed={current?.id===p.id} onClick={()=>applyPreset(p)}><b>{number(p.balls.fairy)} / {number(p.balls.advanced)} / {number(p.balls.net)}</b><span>{en?'Income':'收入'} ×{p.income_multiplier_scenario}</span></button>)}</div>
   <p className="rco-fine">{en?'Presets read: Fairy / Advanced / Net.':'预设依次为：童话球 / 高级咕噜球 / 网兜球。'}</p>
   <div className="rco-ball-inputs">{BALL_KEYS.map((key,i)=>{const invalid=!/^\d+$/.test(state.raw[key].trim());return <label key={key} htmlFor={`${id}-${key}`}><span className="rco-ball-index">0{i+1}</span><span className="rco-ball-label"><b>{text(ballNames[key],lang)}</b><small>{number(calibration[key].unit_price)} {en?'each':'洛克贝 / 个'}</small></span><input id={`${id}-${key}`} type="text" inputMode="numeric" autoComplete="off" value={state.raw[key]} aria-invalid={invalid||result.status==='invalid'} aria-describedby={`${id}-validation`} onChange={e=>setState(s=>({...s,raw:{...s.raw,[key]:e.target.value}}))}/></label>;})}</div>
   <fieldset className="rco-income-toggle"><legend>{en?'Income basis':'收入口径'}</legend>{[1,2].map(mult=><button type="button" key={mult} aria-pressed={state.multiplier===mult} onClick={()=>setState(s=>({...s,multiplier:mult}))}>×{mult}<span>{mult===1?(en?'As recorded':'原始账面'):(en?'Co-op scenario':'牵手折算情景')}</span></button>)}</fieldset>
   <p className="rco-fine">{en?'Use ×1 if the recorded income already includes both players. ×2 changes income only; personal ball cost is never doubled.':'账面收入已含双方时使用 ×1。×2 仅折算收入，本人球成本不翻倍。'}</p>
   <p id={`${id}-validation`} className={`rco-input-message ${result.status}`} role="status">{result.status==='invalid'?(en?'Enter valid nonnegative whole numbers. Empty or fractional values are not converted to zero.':'请输入有效的非负整数；空值、小数与负数不会被转换成 0。'):result.status==='empty'?(en?'No inputs yet. Outcomes remain blank.':'尚未配置投入，结果显示为 —。'):(en?`${number(out.total_balls)} balls configured.`:`当前投入 ${number(out.total_balls)} 球。`)}</p>
   <button type="button" className="rco-text-action" onClick={()=>setState({raw:{fairy:'0',advanced:'0',net:'0'},multiplier:state.multiplier})}>{en?'Clear inputs':'清空投入'} ↺</button>
  </div>
  <div className="rco-calc-results" aria-label={en?'Model expectations':'模型期望'}><div className="rco-panel-heading"><span className="rco-kicker">EXPECTATION / 02</span><h3>{en?'Read the assumptions, too.':'结果，也带着条件。'}</h3><p>{en?'An estimate from this dataset, not official game odds.':'这组数据下的估计，不是官方游戏概率。'}</p></div>
   <div className="rco-result-main"><div><span>{en?'Expected shiny records':'期望异色记录数'}</span><strong>{ready?number(out.expected_shiny_records,2):'—'}</strong><small>{en?'Model expectation':'模型期望'}</small></div><div><span>{en?'At least one · hypothetical':'至少一次 · 假设概率'}</span><strong>{ready?number(out.probability_at_least_one_under_assumptions*100,1):'—'}{ready&&<i>%</i>}</strong><div className="rco-probability-track" aria-hidden="true"><i style={{width:`${ready?out.probability_at_least_one_under_assumptions*100:0}%`}}/></div></div></div>
   <div className="rco-results-secondary"><div><span>{en?'Personal ball cost':'本人球成本'}</span><b>{out?money(out.personal_ball_cost,lang):'—'}</b></div><div><span>{en?'Expected net · conditional':'条件期望净额'}</span><b>{ready?money(out.expected_conditional_net,lang):'—'}</b></div><div><span>{en?'Expected clover sketches':'期望四叶草铅绘'}</span><b>{ready?number(out.expected_material,1):'—'}</b></div><div><span>{en?'Income / ball cost':'期望收入 / 球成本'}</span><b>{ready?number(out.expected_income_cost_ratio,2)+'×':'—'}</b></div></div>
   <div className="rco-money-bars">{[['personal_ball_cost',en?'Ball cost':'球成本'],['expected_conditional_income',en?'Converted expected income':'折算期望收入']].map(([key,label])=><div key={key}><span>{label}<b>{ready?money(out[key],lang):'—'}</b></span><div><i style={{width:`${ready?out[key]/Math.max(out.personal_ball_cost,out.expected_conditional_income)*100:0}%`}}/></div></div>)}</div>
   <p className="rco-fine">{en?'Currency: Roco currency. Net = expected income × selected multiplier − personal ball cost. This is not audited profit.':'金额单位：洛克贝。净额 = 期望收入 × 所选倍率 − 本人球成本，不是已审计实际利润。'}</p>
   <p className="rco-limit">{en?'10 nonrandom observed batches. Fixed-rate, independent-trial assumptions; simulations do not add observed evidence.':'10 批非随机观察。采用固定产出率、独立投入假设；模拟不增加观察证据。'}</p>
   {!compact&&<details className="rco-details"><summary>{en?'Full precision & intermediate values':'查看完整精度与中间值'} <span>＋</span></summary><dl>{[['expected_shiny_records',en?'Expected records':'期望异色记录'],['probability_at_least_one_under_assumptions',en?'Hypothetical probability':'假设概率'],['expected_material',en?'Expected material':'期望材料'],['expected_raw_income',en?'Expected raw income':'期望原始账面收入'],['expected_conditional_income',en?'Converted expected income':'折算期望收入'],['expected_conditional_net',en?'Conditional expected net':'条件期望净额']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{ready?String(out[key]):'—'}</dd></div>)}</dl></details>}
  </div>
 </div>;
}

export function RecordLedger({lang='zh',observedOnly=false}) {
 const en=lang==='en';const [kind,setKind]=useState('observed'),[selected,setSelected]=useState('TEST-01');
 const rows=kind==='observed'?observed:simulations;const row=rows.find(r=>r.id===selected)||rows[0];const isObserved=kind==='observed';
 const chooseKind=k=>{setKind(k);setSelected(k==='observed'?'TEST-01':'SIM-01');};
 const picture=isObserved?recordImage(row.id):null;
 return <div className="rco-ledger">
  {!observedOnly&&<div className="rco-tabs" aria-label={en?'Record type':'记录类型'}>{[['observed',en?'10 observed batches':'10 批观察'],['simulated',en?'10 saved simulations':'10 组固定模拟']].map(([key,label])=><button type="button" key={key} aria-pressed={kind===key} onClick={()=>chooseKind(key)}>{label}</button>)}</div>}
  <p className="rco-fine">{isObserved?(en?'Author’s gameplay records. Select a batch to inspect inputs, original amounts and source cells.':'作者实机记录。选择批次查看投入、原始金额与来源单元格。'):(en?`Saved model draws · seed ${data.seed}. Only shiny counts were sampled; material and income remain expectations. These are not 10 additional observations.`:`已保存模型抽样 · 种子 ${data.seed}。只有异色计数随机抽样；材料、收入为期望值，不是新增 10 批实测。`)}</p>
  <div className="rco-ledger-layout"><div className="rco-table-scroll"><table><thead><tr><th>{en?'Batch':'批次'}</th><th>{en?'Balls':'球数'}</th><th>{isObserved?(en?'Recorded shiny':'异色记录'):(en?'Model draw':'假设抽样')}</th><th>{isObserved?(en?'Material':'材料记录'):(en?'Expected material':'期望材料')}</th></tr></thead><tbody>{rows.map(item=><tr key={item.id} className={row.id===item.id?'selected':''}><th><button type="button" aria-pressed={row.id===item.id} onClick={()=>setSelected(item.id)}>{item.id}<span>↗</span></button></th><td>{number(item.total_balls)}</td><td>{isObserved?item.shiny_records_observed:item.shiny_count_model_draw}</td><td>{isObserved?item.material_observed:number(item.expected.expected_material,1)}</td></tr>)}</tbody></table></div>
   <section className="rco-record-detail" aria-label={`${row.id} ${en?'details':'详情'}`}><div className="rco-record-title"><span className="rco-kicker">{isObserved?'OBSERVED':'SIMULATION / NOT OBSERVED'}</span><h4>{row.id}</h4><p>{isObserved?(row.eligible_for_calibration?(en?'Single-ball batch · used for calibration':'纯球种批次 · 进入校准'):(en?'Mixed batch · excluded from calibration':'混合批次 · 不进入校准')):(en?`Same inputs as ${row.parent_batch_id}; no new observation.`:`沿用 ${row.parent_batch_id} 的投入，不是新观察。`)}</p></div>
   <dl className="rco-record-values">{BALL_KEYS.map(key=><div key={key}><dt>{text(ballNames[key],lang)}</dt><dd>{number(row.balls[key])}</dd></div>)}<div><dt>{en?'Personal ball cost':'本人球成本'}</dt><dd>{number(row.personal_ball_cost)}</dd></div><div><dt>{isObserved?(en?'Recorded raw income':'原始账面收入'):(en?'Expected raw income':'期望原始收入')}</dt><dd>{number(isObserved?row.raw_income_observed:row.expected.expected_raw_income,isObserved?0:2)}</dd></div>{isObserved?<><div><dt>{en?'Recorded Picture Book income':'已记录绘本收入'}</dt><dd>{number(row.picture_book_income_observed)}</dd></div><div><dt>{en?'Raw income excluding recorded books':'剔除已记录绘本的原收入'}</dt><dd>{number(row.raw_income_excluding_recorded_book)}</dd></div></>:<><div><dt>{en?'Expected shiny records':'期望异色记录数'}</dt><dd>{number(row.expected.expected_shiny_records,3)}</dd></div><div><dt>{en?'Conditional net · income ×2':'条件净额 · 收入 ×2'}</dt><dd>{number(row.expected.expected_conditional_net,2)}</dd></div></>}</dl>
   {row.id==='TEST-01'&&<p className="rco-limit">{en?'The 5,400,000 difference between the yellow total and visible white subtotals is unresolved. It is not reassigned as book or ordinary income.':'黄色总额与白字分项相差 5,400,000，来源未归因，不擅自划为绘本或普通收入。'}</p>}
   {isObserved&&<details className="rco-details"><summary>{en?'Original note · Chinese':'原始备注'} <span>＋</span></summary><p>{row.source_note}</p></details>}
   {picture&&<a className="rco-source-image" href={picture} target="_blank" rel="noreferrer"><img src={picture} alt={en?`${row.id} original gameplay record`:`${row.id} 原始实机记录`} loading="lazy"/><span>{en?'Open original screenshot':'查看原始截图'} ↗</span></a>}
   {isObserved&&!picture&&<p className="rco-fine">{en?'The original batch remains in the source ledger and appendix.':'原始批次保留在来源台账与完整附录。'}</p>}
   <details className="rco-details"><summary>{en?'Source cells & classification':'来源单元格与类型'} <span>＋</span></summary><p>{isObserved?(en?'Observed source; not a dated gameplay log. Recording date is not established as capture time.':'作者观察来源；登记日期不等于已经确认的拍摄或游戏时间。'):(en?'Inputs are inherited from the observed parent. This row never enters calibration or observed totals.':'仅继承对应观察的投入。本行不参与校准或观察汇总。')}</p><pre>{JSON.stringify(row.source_cells,null,2)}</pre></details>
   </section></div>
 </div>;
}

export function ModelBasis({lang='zh'}) {
 const en=lang==='en';
 return <div className="rco-model-basis"><p className="rco-lead">{en?'Six single-ball batches supply the coefficients. The other four remain observations, without assigning their mixed outcomes to a ball type.':'六批纯球种记录提供系数。另四批保留为混合观察，不拆分其产出归属。'}</p>
  <div className="rco-table-scroll"><table><thead><tr><th>{en?'Ball type':'球种'}</th><th>{en?'Batches':'批次'}</th><th>N</th><th>Y</th><th>M</th><th>R</th></tr></thead><tbody>{BALL_KEYS.map(key=>{const c=calibration[key];return <tr key={key}><th>{text(ballNames[key],lang)}</th><td>{c.batch_count}</td><td>{number(c.balls)}</td><td>{c.shiny_records}</td><td>{c.material}</td><td>{number(c.raw_income)}</td></tr>;})}</tbody></table></div>
  <p className="rco-fine">{en?'N = balls; Y = shiny records; M = clover sketches; R = recorded raw income. Use exact integer ratios. Y/N is a records-per-ball coefficient, not official odds.':'N = 球数；Y = 异色记录；M = 四叶草铅绘；R = 原始账面收入。使用精确整数比值，Y/N 是记录／耗球系数，不是官方概率。'}</p>
  <div className="rco-formula-grid"><article><span>01 / EXPECTATION</span><code>E[Y] = Σ nₖ · Yₖ/Nₖ</code><code>E[M] = Σ nₖ · Mₖ/Nₖ</code><code>E[R] = Σ nₖ · Rₖ/Nₖ</code><p>{en?'Expectations add across ball types. Mixed-ball interactions, order and shared progress have not been validated.':'各球种期望相加；实际混球交互、顺序和共同进度未经验证。'}</p></article><article><span>02 / PROBABILITY</span><code>P(≥1) = 1 − Π(1 − Yₖ/Nₖ)ⁿᵏ</code><code>X = Σ Binomial(nₖ, Yₖ/Nₖ)</code><p>{en?'Both rely on independent trials and fixed rates. X appears only in the saved simulation ledger; the calculator does not reroll outcomes.':'均依赖独立投入与固定产出率。X 只用于已保存模拟台账，演算台不重抽结果。'}</p></article><article><span>03 / COST & INCOME</span><code>C = Σ nₖ · priceₖ</code><code>{en?'Net':'净额'} = E[R] · m − C</code><code>{en?'Income/cost':'收入/成本'} = E[R] · m / C</code><p>{en?'m is income ×1 or ×2; cost stays personal ×1. Use ×1 when income already contains both players. C = 0 leaves the ratio undefined.':'m 为收入 ×1／×2，本人球成本始终 ×1。收入已含双方时选 ×1；C = 0 时比值不适用。'}</p></article></div>
  <div className="rco-method-notes">{[
   [en?'What the sample cannot establish':'样本不能证明什么',en?'Ten nonrandom batches vary by goal, route, form and stopping rule. Missing event-source labels and completed-encounter denominators prevent estimating the ordinary-encounter base rate. No confidence intervals are implied.':'10 批非随机记录的目标、路线、形态与停手规则不同。逐条异色来源及奇遇完成分母缺失，不能反推普通奇遇基础率，不提供真实概率区间。'],
   [en?'Material & unmodeled income':'材料与未建模收入',en?'Four-leaf Clover Sketches were labeled 草团子 in the original table. An expectation of 30 is neither a guaranteed actual trigger nor a shiny guarantee. Picture Book income is not modeled; TEST-08 and TEST-10 retain recorded book income.':'四叶草铅绘在原表记作“草团子”。期望达到 30 不代表实际必定触发，更不是异色保底。模型不生成绘本收入，TEST-08、10 保留各自已记录绘本收入。'],
   [en?'Fixed simulations, not new evidence':'固定模拟，不增加证据',en?`The saved NumPy PCG64(${data.seed}) run made 14 nonzero binomial calls, SIM-01 to SIM-10, Fairy/Advanced/Net order. Only shiny counts were sampled. No rerolls or added calibration samples.`:`已保存 NumPy PCG64(${data.seed}) 一次执行，共 14 次非零二项调用；顺序 SIM-01–10，每行童话／高级／网兜。只有异色计数抽样，不重抽、不新增校准样本。`],
  ].map(([heading,body])=><details className="rco-details" key={heading}><summary>{heading}<span>＋</span></summary><p>{body}</p></details>)}</div>
 </div>;
}

export default function RocoModel({lang='zh',reduced=false,onNavigate}) {
 const en=lang==='en';
 return <article className={`rco-page rco-model-page${reduced?' rco-reduced':''}`} data-nav-tone="light">
  <header className="rco-model-header rco-width"><button className="rco-back" type="button" onClick={()=>onNavigate?.('/systems/roco')}>← {en?'Back to the case':'返回洛克案例'}</button><div className="rco-model-heading"><div><span className="rco-kicker">S3 / AN INSPECTABLE MODEL</span><h1><ExpressiveTitle reduced={reduced}>{en?<>Inputs.<br/><em>Outcomes.</em></>:<>投入。<br/><em>与结果。</em></>}</ExpressiveTitle></h1></div><div><p>{en?'Change the inputs. Keep the evidence in view.':'改变投入，也看清依据。'}</p><p className="rco-fine">{en?'Three ball types, four audited presets, 10 observations and 10 saved model scenarios.':'三类球，四组已核验预设，10 批观察与 10 组固定模型情景。'}</p><span className="rco-model-version">V6 / {data.version} · {en?'Currency: Roco currency':'金额单位：洛克贝'}</span></div></div></header>
  <div className="rco-width"><ModelCalculator lang={lang}/></div>
  <section className="rco-section rco-width" id="roco-records"><div className="rco-section-label"><b>01</b><span>{en?'THE LEDGER':'观察与模拟'}</span></div><div className="rco-section-body"><h2><ExpressiveTitle reduced={reduced}>{en?'Twenty entries. Ten observations.':'20 条记录，10 批观察。'}</ExpressiveTitle></h2><RecordLedger lang={lang}/></div></section>
  <section className="rco-section rco-width" id="roco-method"><div className="rco-section-label"><b>02</b><span>{en?'METHOD & LIMITS':'公式与边界'}</span></div><div className="rco-section-body"><h2><ExpressiveTitle reduced={reduced}>{en?'A model you can inspect.':'每个数字，都可追溯。'}</ExpressiveTitle></h2><ModelBasis lang={lang}/><div className="rco-link-row"><a href="/assets/roco/model-data.json" download>{en?'Download inputs & saved results':'下载数据与已保存结果'} ↗</a><a href="https://dlarkus6pgedgdu9.usttp.larksuite.com/sheets/WOwMsTmhnhjyLot5tfxuhWdntrh" target="_blank" rel="noreferrer">{en?'Original model · Chinese':'原始模型母版 · 中文'} ↗</a><a href="/assets/docs/roco-appendix.pdf" target="_blank" rel="noreferrer">{en?'Full appendix · Chinese':'完整附录 · 中文'} ↗</a></div></div></section>
  <footer className="rco-page-footer rco-width"><span>S3 / RECORDS ARE NOT ODDS.</span><button type="button" onClick={()=>onNavigate?.('/systems/roco')}>{en?'Return to the design decisions':'回到设计判断'} ↗</button></footer>
 </article>;
}
