// Source-backed portfolio content. Original website is unchanged.
// Art names/slugs: src/data/portfolio.ts; translations/project summaries: V12 content audit.
// New featured descriptions describe only visible image content.
export const allWorks = [
  {
    "id": "world-tree",
    "slug": "world-tree",
    "title": "世界树",
    "titleEn": "World Tree",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "古老巨树、云海与暮光，构成一个可以走进去的幻想世界。",
    "descriptionEn": "An ancient tree, a sea of clouds and evening light shape an imagined world.",
    "year": "2025",
    "type": "personal",
    "image": "/assets/art/world-tree.png",
    "src": "/assets/art/world-tree.png",
    "href": "/works/world-tree",
    "sourceTitle": "World Tree"
  },
  {
    "id": "sakura-village",
    "slug": "sakura-village",
    "title": "樱花村",
    "titleEn": "Sakura Village",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "沿水而建的村落，在樱花、山影和薄雾之间展开。",
    "descriptionEn": "A village unfolds along the water, framed by blossoms, mountains and mist.",
    "year": "2025",
    "type": "personal",
    "image": "/assets/art/sakura-village.png",
    "src": "/assets/art/sakura-village.png",
    "href": "/works/sakura-village",
    "sourceTitle": "Sakura Village"
  },
  {
    "id": "enchanted-forest",
    "slug": "enchanted-forest",
    "title": "秘境森林",
    "titleEn": "Enchanted Forest",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "秘境森林 · 个人创作",
    "descriptionEn": "Deep forest environment with ethereal lighting and mystical atmosphere.",
    "year": "2024",
    "type": "personal",
    "image": "/assets/art/enchanted-forest.png",
    "src": "/assets/art/enchanted-forest.png",
    "href": "/works/enchanted-forest",
    "sourceTitle": "Enchanted Forest"
  },
  {
    "id": "sword-immortal",
    "slug": "sword-immortal",
    "title": "剑仙",
    "titleEn": "Sword Immortal",
    "category": "角色设计",
    "categoryEn": "Character Design",
    "description": "剑仙 · 个人创作",
    "descriptionEn": "Wuxia character design — a swordsman ascending through celestial realms.",
    "year": "2024",
    "type": "personal",
    "image": "/assets/art/sword-immortal.png",
    "src": "/assets/art/sword-immortal.png",
    "href": "/works/sword-immortal",
    "sourceTitle": "Sword Immortal"
  },
  {
    "id": "personal-project",
    "slug": "personal-project",
    "title": "个人创作",
    "titleEn": "Personal Project",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "个人创作 · 个人创作",
    "descriptionEn": "Narrative visual development exploring cinematic storytelling through image-making.",
    "year": "2024",
    "type": "personal",
    "image": "/assets/art/personal-project.jpg",
    "src": "/assets/art/personal-project.jpg",
    "href": "/works/personal-project",
    "sourceTitle": "Personal Project"
  },
  {
    "id": "temple-sketch",
    "slug": "temple-sketch",
    "title": "山寺草图",
    "titleEn": "Temple Sketch",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "山寺草图 · 个人创作",
    "descriptionEn": "Architectural concept — traditional temple in misty mountains.",
    "year": "2024",
    "type": "personal",
    "image": "/assets/art/temple-sketch.jpg",
    "src": "/assets/art/temple-sketch.jpg",
    "href": "/works/temple-sketch",
    "sourceTitle": "Temple Sketch"
  },
  {
    "id": "artist-portrait",
    "slug": "artist-portrait",
    "title": "艺术家肖像",
    "titleEn": "Artist Portrait",
    "category": "角色设计",
    "categoryEn": "Character Design",
    "description": "艺术家肖像 · 个人创作",
    "descriptionEn": "Character portrait study exploring personality and expression.",
    "year": "2025",
    "type": "personal",
    "image": "/assets/art/artist-portrait.png",
    "src": "/assets/art/artist-portrait.png",
    "href": "/works/artist-portrait",
    "sourceTitle": "Artist Portrait"
  },
  {
    "id": "environment-study-i",
    "slug": "environment-study-i",
    "title": "场景研究 I",
    "titleEn": "Environment Study I",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "场景研究 I · 课程作品",
    "descriptionEn": "Academic environment painting exploring composition and color temperature.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/environment-study-i.png",
    "src": "/assets/art/environment-study-i.png",
    "href": "/works/environment-study-i",
    "sourceTitle": "Environment Study I"
  },
  {
    "id": "environment-study-ii",
    "slug": "environment-study-ii",
    "title": "场景研究 II",
    "titleEn": "Environment Study II",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "场景研究 II · 课程作品",
    "descriptionEn": "Environment study focused on atmospheric perspective and depth.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/environment-study-ii.png",
    "src": "/assets/art/environment-study-ii.png",
    "href": "/works/environment-study-ii",
    "sourceTitle": "Environment Study II"
  },
  {
    "id": "environment-study-iii",
    "slug": "environment-study-iii",
    "title": "场景研究 III",
    "titleEn": "Environment Study III",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "场景研究 III · 课程作品",
    "descriptionEn": "Environment study exploring natural lighting and terrain forms.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/environment-study-iii.png",
    "src": "/assets/art/environment-study-iii.png",
    "href": "/works/environment-study-iii",
    "sourceTitle": "Environment Study III"
  },
  {
    "id": "environment-study-iv",
    "slug": "environment-study-iv",
    "title": "场景研究 IV",
    "titleEn": "Environment Study IV",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "场景研究 IV · 课程作品",
    "descriptionEn": "Environment study with emphasis on mood and spatial design.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/environment-study-iv.png",
    "src": "/assets/art/environment-study-iv.png",
    "href": "/works/environment-study-iv",
    "sourceTitle": "Environment Study IV"
  },
  {
    "id": "character-vis-dev",
    "slug": "character-vis-dev",
    "title": "角色视觉开发",
    "titleEn": "Character Vis Dev",
    "category": "角色设计",
    "categoryEn": "Character Design",
    "description": "从轮廓探索到最终造型，记录 Alaric 的角色视觉开发。",
    "descriptionEn": "Silhouette explorations and a final design trace the visual development of Alaric.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/character-vis-dev.png",
    "src": "/assets/art/character-vis-dev.png",
    "href": "/works/character-vis-dev",
    "sourceTitle": "Character Vis Dev"
  },
  {
    "id": "prop-design",
    "slug": "prop-design",
    "title": "道具设计",
    "titleEn": "Prop Design",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "道具设计 · 课程作品",
    "descriptionEn": "Prop design exploring form language and material storytelling.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/prop-design.png",
    "src": "/assets/art/prop-design.png",
    "href": "/works/prop-design",
    "sourceTitle": "Prop Design"
  },
  {
    "id": "vehicle-design",
    "slug": "vehicle-design",
    "title": "载具设计",
    "titleEn": "Vehicle Design",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "载具设计 · 课程作品",
    "descriptionEn": "Vehicle concept design blending function and narrative context.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/vehicle-design.png",
    "src": "/assets/art/vehicle-design.png",
    "href": "/works/vehicle-design",
    "sourceTitle": "Vehicle Design"
  },
  {
    "id": "visual-development-i",
    "slug": "visual-development-i",
    "title": "视觉开发 I",
    "titleEn": "Visual Development I",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "视觉开发 I · 课程作品",
    "descriptionEn": "Visual development piece exploring narrative through image-making.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/visual-development-i.jpg",
    "src": "/assets/art/visual-development-i.jpg",
    "href": "/works/visual-development-i",
    "sourceTitle": "Visual Development I"
  },
  {
    "id": "visual-development-ii",
    "slug": "visual-development-ii",
    "title": "视觉开发 II",
    "titleEn": "Visual Development II",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "视觉开发 II · 课程作品",
    "descriptionEn": "Continuation of visual development narrative studies.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/visual-development-ii.jpg",
    "src": "/assets/art/visual-development-ii.jpg",
    "href": "/works/visual-development-ii",
    "sourceTitle": "Visual Development II"
  },
  {
    "id": "visual-development-iii",
    "slug": "visual-development-iii",
    "title": "视觉开发 III",
    "titleEn": "Visual Development III",
    "category": "视觉开发",
    "categoryEn": "Visual Development",
    "description": "视觉开发 III · 课程作品",
    "descriptionEn": "Visual development exploring cinematic framing and storytelling.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/visual-development-iii.jpg",
    "src": "/assets/art/visual-development-iii.jpg",
    "href": "/works/visual-development-iii",
    "sourceTitle": "Visual Development III"
  },
  {
    "id": "creative-perspective",
    "slug": "creative-perspective",
    "title": "创意透视",
    "titleEn": "Creative Perspective",
    "category": "基础训练",
    "categoryEn": "Fundamentals",
    "description": "创意透视 · 课程作品",
    "descriptionEn": "Perspective fundamentals applied to creative scene composition.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/creative-perspective.jpg",
    "src": "/assets/art/creative-perspective.jpg",
    "href": "/works/creative-perspective",
    "sourceTitle": "Creative Perspective"
  },
  {
    "id": "creative-perspective-ii",
    "slug": "creative-perspective-ii",
    "title": "创意透视 II",
    "titleEn": "Creative Perspective II",
    "category": "基础训练",
    "categoryEn": "Fundamentals",
    "description": "创意透视 II · 课程作品",
    "descriptionEn": "Advanced perspective study with architectural subjects.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/creative-perspective-ii.png",
    "src": "/assets/art/creative-perspective-ii.png",
    "href": "/works/creative-perspective-ii",
    "sourceTitle": "Creative Perspective II"
  },
  {
    "id": "background-painting",
    "slug": "background-painting",
    "title": "背景绘画",
    "titleEn": "Background Painting",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "雪覆木屋与粉紫色的晚霞，以色温和层次建立场景气氛。",
    "descriptionEn": "Snow-covered timber houses and a pink-violet sky build atmosphere through color and depth.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/background-painting.png",
    "src": "/assets/art/background-painting.png",
    "href": "/works/background-painting",
    "sourceTitle": "Background Painting"
  },
  {
    "id": "mars-monster",
    "slug": "mars-monster",
    "title": "火星怪物",
    "titleEn": "Mars Monster",
    "category": "角色设计",
    "categoryEn": "Character Design",
    "description": "火星怪物 · 课程作品",
    "descriptionEn": "Creature design exploring alien biology and hostile environments.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/mars-monster.png",
    "src": "/assets/art/mars-monster.png",
    "href": "/works/mars-monster",
    "sourceTitle": "Mars Monster"
  },
  {
    "id": "3d-modeling-maya",
    "slug": "3d-modeling-maya",
    "title": "3D 建模 — Maya",
    "titleEn": "3D Modeling — Maya",
    "category": "三维创作",
    "categoryEn": "3D",
    "description": "3D 建模 — Maya · 课程作品",
    "descriptionEn": "3D modeling study using Autodesk Maya.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/3d-modeling-maya.png",
    "src": "/assets/art/3d-modeling-maya.png",
    "href": "/works/3d-modeling-maya",
    "sourceTitle": "3D Modeling — Maya"
  },
  {
    "id": "3d-modeling-maya-ii",
    "slug": "3d-modeling-maya-ii",
    "title": "3D 建模 — Maya II",
    "titleEn": "3D Modeling — Maya II",
    "category": "三维创作",
    "categoryEn": "3D",
    "description": "3D 建模 — Maya II · 课程作品",
    "descriptionEn": "Continued 3D modeling exploration in Maya.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/3d-modeling-maya-ii.png",
    "src": "/assets/art/3d-modeling-maya-ii.png",
    "href": "/works/3d-modeling-maya-ii",
    "sourceTitle": "3D Modeling — Maya II"
  },
  {
    "id": "cat-diary",
    "slug": "cat-diary",
    "title": "猫咪日记",
    "titleEn": "Cat Diary",
    "category": "插画",
    "categoryEn": "Illustration",
    "description": "猫咪日记 · 课程作品",
    "descriptionEn": "Narrative illustration series exploring daily moments through a feline lens.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/cat-diary.png",
    "src": "/assets/art/cat-diary.png",
    "href": "/works/cat-diary",
    "sourceTitle": "Cat Diary"
  },
  {
    "id": "sketching-for-entd",
    "slug": "sketching-for-entd",
    "title": "娱乐设计速写",
    "titleEn": "Sketching for ENTD",
    "category": "基础训练",
    "categoryEn": "Fundamentals",
    "description": "娱乐设计速写 · 课程作品",
    "descriptionEn": "Foundational sketching studies for entertainment design.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/sketching-for-entd.png",
    "src": "/assets/art/sketching-for-entd.png",
    "href": "/works/sketching-for-entd",
    "sourceTitle": "Sketching for ENTD"
  }
];

export const featuredWorks = [
  {
    "id": "world-tree",
    "slug": "world-tree",
    "title": "世界树",
    "titleEn": "World Tree",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "古老巨树、云海与暮光，构成一个可以走进去的幻想世界。",
    "descriptionEn": "An ancient tree, a sea of clouds and evening light shape an imagined world.",
    "year": "2025",
    "type": "personal",
    "image": "/assets/art/world-tree.png",
    "src": "/assets/art/world-tree.png",
    "href": "/works/world-tree",
    "sourceTitle": "World Tree"
  },
  {
    "id": "background-painting",
    "slug": "background-painting",
    "title": "背景绘画",
    "titleEn": "Background Painting",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "雪覆木屋与粉紫色的晚霞，以色温和层次建立场景气氛。",
    "descriptionEn": "Snow-covered timber houses and a pink-violet sky build atmosphere through color and depth.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/background-painting.png",
    "src": "/assets/art/background-painting.png",
    "href": "/works/background-painting",
    "sourceTitle": "Background Painting"
  },
  {
    "id": "sakura-village",
    "slug": "sakura-village",
    "title": "樱花村",
    "titleEn": "Sakura Village",
    "category": "场景设计",
    "categoryEn": "Environment Design",
    "description": "沿水而建的村落，在樱花、山影和薄雾之间展开。",
    "descriptionEn": "A village unfolds along the water, framed by blossoms, mountains and mist.",
    "year": "2025",
    "type": "personal",
    "image": "/assets/art/sakura-village.png",
    "src": "/assets/art/sakura-village.png",
    "href": "/works/sakura-village",
    "sourceTitle": "Sakura Village"
  },
  {
    "id": "character-vis-dev",
    "slug": "character-vis-dev",
    "title": "角色视觉开发",
    "titleEn": "Character Vis Dev",
    "category": "角色设计",
    "categoryEn": "Character Design",
    "description": "从轮廓探索到最终造型，记录 Alaric 的角色视觉开发。",
    "descriptionEn": "Silhouette explorations and a final design trace the visual development of Alaric.",
    "year": "2024",
    "type": "school",
    "image": "/assets/art/character-vis-dev.png",
    "src": "/assets/art/character-vis-dev.png",
    "href": "/works/character-vis-dev",
    "sourceTitle": "Character Vis Dev"
  }
];

const verifiedProjects = [
  {
    "id": "roco",
    "slug": "roco",
    "title": "洛克王国：世界",
    "titleEn": "Roco Kingdom: World",
    "subtitle": "异色系统研究",
    "subtitleEn": "Shiny systems study",
    "description": "拆解 S3 收集循环与投入记录，提出 S5 两套机制，并用交互原型检查状态与结算边界。",
    "descriptionEn": "A study of the S3 collection loop and resource records, followed by two S5 proposals and an interactive prototype for state and settlement rules.",
    "contribution": "系统拆解、10 批观察与成本模型、S5 双方案、交互原型与规则边界检查。",
    "contributionEn": "System mapping, 10 recorded batches and a cost model, two S5 proposals, an interactive prototype, and rule-boundary checks.",
    "classification": "个人研究与原创提案 · 非官方项目",
    "classificationEn": "Personal study and original proposals · Unofficial",
    "image": "/assets/projects/roco-cover.png",
    "href": "/systems/roco",
    "detailAvailable": true,
    "materials": [
      {
        "label": "阅读研究正文 ↗",
        "labelEn": "Read the study ↗",
        "href": "/assets/docs/roco-review.pdf"
      },
      {
        "label": "查看完整附录 ↗",
        "labelEn": "View the appendix ↗",
        "href": "/assets/docs/roco-appendix.pdf"
      },
      {
        "label": "体验 S5 双方案 ↗",
        "labelEn": "Explore the S5 prototype ↗",
        "href": "https://s5-encounter-lab.linke0704.chatgpt.site"
      }
    ]
  },
  {
    "id": "alt-ctrl",
    "slug": "alt-ctrl",
    "title": "alt.ctrl",
    "titleEn": "alt.ctrl",
    "subtitle": "玩法机制与交互",
    "subtitleEn": "Gameplay & interaction",
    "description": "围绕物品声音主题构建实体互动机制，梳理输入、判定与难度，并通过试玩改进引导和反馈。",
    "descriptionEn": "Physical interaction mechanics built around object sounds, with input, rule and difficulty design refined through playtesting and feedback.",
    "contribution": "玩法机制与交互设计、试玩迭代，以及角色选择、新手引导和游戏反馈界面。",
    "contributionEn": "Gameplay and interaction design, playtest iteration, and character-selection, onboarding and gameplay-feedback interfaces.",
    "classification": "团队项目 · 玩法与交互设计",
    "classificationEn": "Team project · Gameplay and interaction design",
    "image": null,
    "href": "/systems#alt-ctrl",
    "detailAvailable": false,
    "materials": [
      {
        "label": "查看简历中的项目经历 ↗",
        "labelEn": "View résumé experience ↗",
        "href": "/assets/docs/jay-lin-systems-resume-zh.pdf"
      }
    ]
  },
  {
    "id": "2xko",
    "slug": "2xko",
    "title": "2XKO",
    "titleEn": "2XKO",
    "subtitle": "玩法测试与体验分析",
    "subtitleEn": "Playtesting & experience analysis",
    "description": "通过结构化试玩拆解 Tag 换人、Assist 支援与 Fuse 组合，分析新手理解断层并提出反馈建议。",
    "descriptionEn": "Structured playtesting of Tag, Assist and Fuse interactions, identifying gaps in newcomer understanding and proposing clearer feedback.",
    "contribution": "机制拆解、体验问题定位、引导与反馈建议，以及书面分析。",
    "contributionEn": "Mechanic analysis, experience-issue identification, onboarding and feedback recommendations, and written analysis.",
    "classification": "玩法测试与体验分析经历",
    "classificationEn": "Playtesting and experience-analysis work",
    "image": null,
    "href": "/systems#2xko",
    "detailAvailable": false,
    "materials": [
      {
        "label": "查看简历中的项目经历 ↗",
        "labelEn": "View résumé experience ↗",
        "href": "/assets/docs/jay-lin-systems-resume-zh.pdf"
      }
    ]
  },
  {
    "id": "isola",
    "slug": "isola",
    "title": "ISOLA: Four Keys Oath",
    "titleEn": "ISOLA: Four Keys Oath",
    "subtitle": "原创 IP 与世界构建",
    "subtitleEn": "Original IP & worldbuilding",
    "description": "搭建原创奇幻 IP 的区域、世界规则与冒险主线，连接资源差异、玩家推进路径和角色成长。",
    "descriptionEn": "An original fantasy IP linking regions, world rules and an adventure storyline with resource differences, player progression and character growth.",
    "contribution": "原创 IP 框架、五个差异化区域、区域资源与推进关系，以及四人主角团队设定。",
    "contributionEn": "Original IP framework, five distinct regions, regional resource and progression relationships, and a four-character lead ensemble.",
    "classification": "原创 IP 内容与视觉开发",
    "classificationEn": "Original IP and visual development",
    "image": null,
    "href": "/systems#isola",
    "detailAvailable": false,
    "materials": [
      {
        "label": "查看简历中的项目经历 ↗",
        "labelEn": "View résumé experience ↗",
        "href": "/assets/docs/jay-lin-systems-resume-zh.pdf"
      }
    ]
  }
];

export const otherProjects = verifiedProjects.filter(project => project.id !== 'roco');
export const systems = [
  { ...verifiedProjects[0], status: 'available' },
  { id: 'league-of-legends', slug: 'league-of-legends', title: '英雄联盟', titleEn: 'League of Legends', subtitle: '活动系统策划', subtitleEn: 'Event systems design', status: 'coming-soon', detailAvailable: false, image: null, description: 'Coming Soon', descriptionEn: 'Coming Soon', classification: '筹备中', classificationEn: 'Coming Soon' },
  { id: 'genshin-impact', slug: 'genshin-impact', title: '原神', titleEn: 'Genshin Impact', subtitle: '抽卡系统策划', subtitleEn: 'Wish systems design', status: 'coming-soon', detailAvailable: false, image: null, description: 'Coming Soon', descriptionEn: 'Coming Soon', classification: '筹备中', classificationEn: 'Coming Soon' },
];

export const author = {
  "name": "林世杰",
  "nameEn": "Jay Lin",
  "role": "系统策划 · 视觉创作",
  "roleEn": "Systems design · Visual storytelling",
  "statement": "我研究目标、规则与反馈，也通过概念设计构建世界。",
  "statementEn": "I explore goals, rules and feedback, and build worlds through concept design.",
  "email": "shijielin00@gmail.com",
  "phone": "+1 626-727-0409",
  "phoneHref": "tel:+16267270409",
  "resume": "/assets/docs/jay-lin-systems-resume-zh.pdf",
  "education": [
    {
      "institution": "ArtCenter College of Design",
      "qualification": "插画本科（娱乐设计方向），辅修商科",
      "qualificationEn": "Bachelor’s degree in Illustration with an Entertainment Design focus; Business minor",
      "period": "2023.09–2026.05"
    },
    {
      "institution": "Duke University, Fuqua School of Business",
      "qualification": "商业管理学硕士在读",
      "qualificationEn": "Master’s in Management candidate",
      "period": "2026.07–2027.05"
    }
  ]
};

export const stats = {
  "archiveWorks": 25,
  "observedBatches": 10,
  "systemProjects": 3,
  "availableSystemProjects": 1,
  "comingSoonProjects": 2,
  "otherProjects": 3
};

export const archiveHref = '/works/archive';
export const ALL_WORKS = allWorks;
export const FEATURED_WORKS = featuredWorks;
export const SYSTEMS_PROJECTS = systems;
export const OTHER_PROJECTS = otherProjects;
